### ISSUE TITLE
Followup schedule button workflow

### ISSUE THREAD

**Issue by rowo** [OpenSRP/tbr5#47]
Moved from: https://projects.invisionapp.com/d/main#/console/11807727/249241054/comments/86598958

For the In-treatment register, users have the option to make the follow-up button follow a schedule. However, a followup can involve one or more tests (recorded at different times) or possibly a unique followup form.

This issue should jdefine the possible workflows for what happens when a schedule-based followup button is clicked.

**Comment by cafootitt** [comment]
I think it should open up a follow-up form. The draft xlsform we have right now for the follow-up visit form is just to say that the patient was seen and to update (or keep the same) their medication regimen. 

So I guess the question is should the follow-up form contain the option to record test results, or should test results be kept separate? 

I seem to recall that follow-up is specifically tied to refilling medications, so not all follow-up visits would have a test result to enter.

**Comment by rowo** [comment]
@kwasim @alihabib Can you guys take a look and agree/disagree to how followup works:

It seems we should handle test results the same way in in-treatment as we do in presumptive/diagnosed and dissociate it from follow-up. The follow-up form is the only one that can be scheduled (not any of the tests).

During presumptive/diagnosed, test results are being added over time, even after diagnosis, until a point where they start treatment. At this point, the initial set of results is the baseline.

During treatment, test results are added and repeated over the treatment period. What's displayed most prominently are the latest results, though there is a baseline vs. latest result module in the detail view.

**Comment by alihabib** [comment]
Just the one note on this: In addition to follow-up form, smears can be scheduled. But that is the only form other than follow-up

All else works really well as described.

**Comment by rowo** [comment]
Great thanks. I guess that means there are two potential scheduled button columns: followups and smears. I can add that as a possible column.
