### ISSUE TITLE
Service History module variations

### ISSUE THREAD

**Issue by rowo** [OpenSRP/tbr5#48]
Initially proposed in https://projects.invisionapp.com/d/main#/console/11807727/249241051/comments/85832931 is a reverse chronological organization. @kwasim and @alihabib brought up adding another organization (or perhaps label) with categories like Registration", "Labs" and maybe "Misc". This issue is to draw out different possibilities.

**Comment by rowo** [comment]
@alihabib @kwasim To close this issue, I think we need your guidance on these questions:

Question 1: Should the Service History in the Presumptive and Diagnosed/Positive registers be in chronological order or reverse chronological? (Ali noted these histories don't have to be categorized.)

Question 2: How do we group these forms within the Registration, Labs and Misc categories?
- registration 
- smear
- treatment outcome
- treatment initation
- screening
- follow up visit
- genexpert
- culture
- xray
- contact screening new person(s)

Question 3: Related to the above, do we have to differentiate between labs done pre-diagnosis vs. post?

**Comment by alihabib** [comment]
Hi...

Responses below:

Question 1): Reverse Chronological is the way to go. Generally the latest
results are most useful.

Question 2) For Patients under treatment, the grouping can be as below:

Registration: screening, registration
Treatment: Treatment Initiation, Follow-up visit, end of outcome
Labs: smear, culture, genepxert, xray (split between diagnostic tests and
post-treatment-initiation  - see response to Q3)
Misc: Contact Screening

Question 3: Yes, differentiating between baseline (i.e pre-diagnosis) and
post labs will be important (see response to Q2 labs)

Ali



Ali Habib
Chief Executive Officer
Interactive Health Solutions
http://www.ihsinformatics.com

ali.habib@ihsinformatics.com

**Comment by rowo** [comment]
Categorization is going to be a secondary requirement only if there's time because the phone version is much smaller than tablet.
