### ISSUE TITLE
Patient did not move from Positive to In Treatment Register when Tx Initiation Form saved

### ISSUE THREAD

**Issue by alihabib** [OpenSRP/tbr5#51]
Patient: Ali Test
ID 666777999

When I filled in Presumptive Form and "Diagnosed" the patient, he correctly disappeared from Presumptive Register and appeared in Positive Register. However, when I filled in the Treatment Initiation Form, the patient stayed in Positive Register and also appeared in In-Treatment register.

However, when I logged back out and logged in the next day, patient is correctly showing only in In-Treatment Register

**Comment by cafootitt** [comment]
This is resolved. Closing.
