### ISSUE TITLE
Treatment Register UI appears distorted

### ISSUE THREAD

**Issue by alihabib** [OpenSRP/tbr5#52]
Screenshot below. The first Results column is active and works as expected. The second results column is inactive.

Also I filled in the Treatment Initiation Form with a date of Dec 27th 2017. When I saved the form, the follow-up cell is red - which indicates overdue. This is odd because the follow-up would be 30 days later so it can't be overdue

![screenshot_20171227-193542](https://user-images.githubusercontent.com/2927914/34400657-6bafcef4-ebb5-11e7-8464-37859266bd4c.jpg)

**Comment by alihabib** [comment]
Just realised that the distortion is due to the fact that the display is 5 columns and not 3
Tested on a 5.5 inch phone screen

**Comment by cafootitt** [comment]
Closing this issue. It is resolved.
